# Generated by Django 5.0.7 on 2024-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='residuos_images/'),
        ),
    ]
