# Generated by Django 5.0.7 on 2024-12-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_residuo_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontocoleta',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='pontocoleta',
            name='tipo_residuo',
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='tipos_residuo',
            field=models.ManyToManyField(related_name='pontos_coleta', to='accounts.residuo'),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
